spacetraveltechnology.energy_group = "spacetraveltechnology_energy";
spacetraveltechnology.energy_connections_meta = "spacetraveltechnology:energy_connections";
spacetraveltechnology.energy_production_left_meta = "spacetraveltechnology:energy_production_left";
spacetraveltechnology.energy_production_initial_meta = "spacetraveltechnology:energy_production_initial";
spacetraveltechnology.energy_production_blacklist_meta = "spacetraveltechnology:energy_production_blacklist_meta";
spacetraveltechnology.is_energy_producer_meta = "spacetraveltechnology:is_energy_producer";
spacetraveltechnology.energy_sources_cache_meta = "spacetraveltechnology:energy_sources_cache";
spacetraveltechnology.conducts_energy_meta = "spacetraveltechnology:conducts_energy";
